### ISSUE TITLE
Removing urls once reached

### ISSUE THREAD

**Issue by derwolfe** [CircleUp/aresponses#13]
Hi! Thanks for writing this!

I was working on integrating this into one of my first aiohttp projects and I could not figure out why the url I'd added was going away after the very first called had reached it. After a little while, I went to read the source and found https://github.com/CircleUp/aresponses/blob/master/aresponses/main.py#L93.

I can definitely see an argument for having this but I think it would be helpful to craft an error message saying why it's been removed. Or, the call to delete the route could simply be removed. 

This functionality is different than every other mock utility I've used. IME the urls are always available and it is left to the caller to establish counts or use some sort of history storage mechanism to verify which paths were hit and how frequently. Overall, I think this behavior is surprising to users and can be somewhat difficult to diagnose. Also, the workaround (at least in my case) has been to add the same url in a loop so that my test can make repeated requests to the same resource. 

What do you think?

Thanks again :)

**Comment by brycedrennan** [comment]
I was trying imitate this functionality: 

https://github.com/getsentry/responses#multiple-responses

I don't have time today to investigate whether aresponses is truly behaving differently but my read of this documentation is that it's behaving as expected.   

I like that it makes our tests more specific by needing to specify the number of expected requests. I also have added urls in loops.

I can imagine some fixes though: 
 - an optional argument that specifies the number of times a response can be served 
 - an optional argument that disables removal
 - better error messages
 - better documentation

I would accept a pull requests with any or all of these improvements.

**Comment by derwolfe** [comment]
Thanks for your quick response! I'll start working on PRs to 

1. document the current behavior
2. add a new behavior to disable removal and document it

:D

**Comment by layday** [comment]
I find myself needing this as well and opened #40 after some head-scratching.

**Comment by brycedrennan** [comment]
@derwolfe I've added a `repeat` argument in proposed 2.0 to address this.  I'd welcome your feedback on this PR: https://github.com/CircleUp/aresponses/pull/45
