### ISSUE TITLE
Add support for callbacks

### ISSUE THREAD

**Issue by marco-c** [CircleUp/aresponses#15]
Callbacks are very useful when you need to test POST requests

**Comment by brycedrennan** [comment]
@marco-c the response can already be a callable.  Does that meet your needs?

**Comment by brycedrennan** [comment]
I've updated the docs to demonstrate using a callable as a response:

https://github.com/p4l1ly/aresponses/blob/89d04862a22e2107ee321593d189ea4f9a6ea41c/README.md#example
