### ISSUE TITLE
AttributeError: module 're' has no attribute '_pattern_type'

### ISSUE THREAD

**Issue by F1ashhimself** [CircleUp/aresponses#17]
This comes with Python 3.7
Now `re.Pattern` should be used instead.

**Comment by brycedrennan** [comment]
Thank you!

**Comment by bradwood** [comment]
Any plans for a new pypy push on this? I just hit this problem myself...

ta

b

**Comment by brycedrennan** [comment]
Pushed 
https://pypi.org/project/aresponses/1.1.1/
