### ISSUE TITLE
Support `pytest_aiohttp`

### ISSUE THREAD

**Issue by ikhlestov** [CircleUp/aresponses#26]
At the present `pytest_aiohttp` doesn't work correct with `pytest_asyncio` ([pytest_aiohttp issue](https://github.com/aio-libs/pytest-aiohttp/issues/8#issuecomment-405602020) and [pytest_asyncio issue](https://github.com/pytest-dev/pytest-asyncio/issues/76) ).
On the other hand `aresponses` doesn't require `pytest_asyncio` directly and can be executed without it. But `aresponses` depends on `event_loop` fixture [here](https://github.com/CircleUp/aresponses/blob/master/aresponses/main.py#L172). So the main questions - can we use existing fixture `event_loop` from asyncio or `loop` from aiohttp on the fly for the `aresponses` fixture initialization?

```python
"""Test script to show aresponses work without pytest_asyncio
Steps:
- install all required packages as `pip install pytest aiohttp pytest_aiohttp aresponses`
- run script as `pytest test_example.py -p no:asyncio
"""
import pytest
import aiohttp


# Simple server definition
async def handle(request):
    return aiohttp.web.Response(text="test response")


def create_app():
    app = aiohttp.web.Application()
    app.add_routes([aiohttp.web.get('/', handle)])
    return app


# Tests
@pytest.fixture
async def client(aiohttp_client):
    app = create_app()
    return await aiohttp_client(app)


async def test_root_url(client):
    resp = await client.get('/')
    assert resp.status == 200
    assert await resp.text() == "test response"


# this additional fixture required by aresponses
# by default aresponses depends on `event_loop` fixture defined at the pytest_asyncio
@pytest.fixture
def event_loop(loop):
    return loop


async def test_aresponses_without_aiohttp(aresponses):
    aresponses.add('foo.com', '/', 'get', 'hi there!!')
    url = 'http://foo.com'
    async with aiohttp.ClientSession() as session:
        async with session.get(url) as response:
            text = await response.text()
            assert text == 'hi there!!'
```

**Comment by brycedrennan** [comment]
If you just define your own fixture in conftest.py will that work?

```python
from aresponses import ResponsesMockServer

@pytest.fixture
async def aresponses(loop):
    async with ResponsesMockServer(loop=loop) as server:
        yield server
```

**Comment by ikhlestov** [comment]
Yes, it works, thank you. I think it's a nice resolution. Should I create a PR with readme update with additional example for aresponses+aiohttp_client or there is no reason for it?

**Comment by brycedrennan** [comment]
That would be great thank you!

**Comment by XayOn** [comment]
Yet pytest-asyncio is included in the setup.py as installs_requires.
Thus provoking the aformentioned bug ( https://github.com/aio-libs/pytest-aiohttp/issues/8 ).

**Comment by XayOn** [comment]
Also, latest pytest releases will await coroutines just fine without pytest-asyncio.

**Comment by brycedrennan** [comment]
@XayOn do you have some documentation that shows pytest now supports asyncio?  I found this which implies it doesn’t. 
https://github.com/pytest-dev/pytest/pull/2175
