### ISSUE TITLE
Allow introspecting captured requests and responses

### ISSUE THREAD

**Issue by gjcarneiro** [CircleUp/aresponses#32]
I want to inspect the headers of the requests.  With the `responses` module I  can do something like this:

```
        assert mocked_responses.calls[1].request.headers["Authorization"] == \
            "Token this-is-token"
```

But `aresponses` doesn't seem to store the requests/responses anywhere.

**Comment by brycedrennan** [comment]
@gjcarneiro  Good idea. I've added this feature in https://github.com/CircleUp/aresponses/pull/45. 

I would appreciate any feedback you have on that pull request.
