### ISSUE TITLE
What are differences from  pytest_plugin.TestServer?

### ISSUE THREAD

**Issue by dz0** [CircleUp/aresponses#48]
Hi, 
found reference to aresponses in https://github.com/aio-libs/aiohttp/issues/1704

but then looked at https://docs.aiohttp.org/en/v0.22.0/testing.html#pytest-example that has very similar purpose.

I see that you have:
 - more flexible request matching
 - `history`. 

Is there sth else that I don't notice?

**Comment by brycedrennan** [comment]
I'm not familiar enough with `pytest_plugin.TestServer` to make a detailed comparison.   I like the API of aresponses better, both for mocking and for assertions.  I think aresponses is different in that you're not just mocking, you're laying out the exact order you expect calls to occur in the mocks themselves are their own kind of assertion.
