### ISSUE TITLE
Raise an error when a request is made to an URL that doesn't hit a match

### ISSUE THREAD

**Issue by marco-c** [CircleUp/aresponses#5]
Similar to `responses`, it's useful to make sure unit tests don't hit the network.

**Comment by brycedrennan** [comment]
Are you saying you wish `aresponses` did this better?

**Comment by marco-c** [comment]
Sorry, my fault. I was trying to use aresponses in a fixture and it didn't work well (aresponses wasn't actually activated for the test).

**Comment by brycedrennan** [comment]
Thanks for the feedback. I haven't used it in a fixture before - sounds like something to investigate.
